services:

  redis:
    image: redis:7-alpine
    container_name: redis-cache
    command: >
      redis-server
      --maxmemory ${CACHE_MAXMEMORY:-2mb}
      --maxmemory-policy ${CACHE_EVICTION_POLICY:-allkeys-lru}
    ports:
      - "6379:6379"

  traffic-generator:
    build: ./traffic-generator
    container_name: traffic-generator
    environment:
      TRAFICO_DISTRIBUCION: ${TRAFICO_DISTRIBUCION:-uniforme}
      TRAFICO_SOLICITUDES: ${TRAFICO_SOLICITUDES:-1000}
      TRAFICO_SEMILLA: ${TRAFICO_SEMILLA:-42}
      TRAFICO_ZIPF_S: ${TRAFICO_ZIPF_S:-1.2}
      TRAFICO_TASA_ARRIBO: ${TRAFICO_TASA_ARRIBO:-10}
      TRAFICO_TIPOS_CONSULTA: ${TRAFICO_TIPOS_CONSULTA:-Q1,Q2,Q3,Q4,Q5}
      CACHE_SERVICE_URL: ${CACHE_SERVICE_URL:-http://cache-service:8000}
      CACHE_TIMEOUT: ${CACHE_TIMEOUT:-5}

  cache-service:
    build: ./cache-service
    container_name: cache-service
    ports:
      - "8000:8000"
    environment:
      METRICS_SERVICE_URL: http://metrics-service:8002
      METRICS_TIMEOUT: 2
      CACHE_TTL: ${CACHE_TTL:-300}
    depends_on:
      - redis
      - scraper-service
      - metrics-service

  scraper-service:
    build: ./scraper-service
    container_name: scraper-service
    ports:
      - "8001:8001"

  metrics-service:
    build: ./metrics-service
    container_name: metrics-service
    ports:
      - "8002:8002"